"""empty message

Revision ID: 811f48a0ad43
Revises: a0f170127436
Create Date: 2021-03-01 20:18:45.651507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811f48a0ad43'
down_revision = 'a0f170127436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
